### ISSUE TITLE
Help | Win Forms

### ISSUE THREAD

**Issue by samuelroliveira** [aspnetboilerplate/aspnetboilerplate-samples#11]
Hello, I am new to C # .

Could you provide an example in Windows Forms ? I tried to reproduce the WPF project code but to no avail .
I appreciate the patience and the time can do .

How would the code in class ' Program' ? This is where dependency injection is started, right?

**Comment by hikalkan** [comment]
Hi,

I created a Windows Forms UI for the same WPF demo: https://github.com/aspnetboilerplate/aspnetboilerplate-samples/tree/master/AbpWpfDemo/AbpWpfDemo.UI-WinForms

**Comment by samuelroliveira** [comment]
Thank you very much. o/
