### ISSUE TITLE
No Readme File

### ISSUE THREAD

**Issue by okezieokpara** [aspnetboilerplate/aspnetboilerplate-samples#13]
This project doesn't have any readme file or reference to its content

**Comment by hikalkan** [comment]
Which project? There are many projects here.

**Comment by okezieokpara** [comment]
The interceptionDemo precisely

**Comment by hikalkan** [comment]
OK, I added it: https://github.com/aspnetboilerplate/aspnetboilerplate-samples/tree/master/InterceptionDemo

Thanks.
