### ISSUE TITLE
Background Workers problem

### ISSUE THREAD

**Issue by dxzcc** [aspnetboilerplate/aspnetboilerplate-samples#14]
The BackgroundJobAndNotificationsDemo Background Workers have a good running.
But when I add the code :
`var workManager = IocManager.Resolve<IBackgroundWorkerManager>();`

in the AbpZeroTemplate,it has a exception:
`No component for supporting the service Abp.Threading.BackgroundWorkers.IBackgroundWorkerManager was found`

What should I do?

**Comment by hikalkan** [comment]
Where did you write this code? We did write here: https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/master/BackgroundJobAndNotificationsDemo/BackgroundJobAndNotificationsDemo.Core/BackgroundJobAndNotificationsDemoCoreModule.cs#L45 and it's working.

**Comment by dxzcc** [comment]
Oh, I'm write the code in the PreInitialize...
I know, thank you very much

**Comment by hikalkan** [comment]
You're welcome.
