### ISSUE TITLE
SimpleTaskSystem-API exception

### ISSUE THREAD

**Issue by nccheckcashing** [aspnetboilerplate/aspnetboilerplate-samples#15]
When I run the SimpleTaskSystem Demo, I got the following error message. 

{"message":"An error has occurred.","exceptionMessage":"There is an action GetTasks defined for api controller tasksystem/task but with a different HTTP Verb. Request verb is GET. It should be Post","exceptionType":"Abp.AbpException","stackTrace":"   at Abp.WebApi.Controllers.Dynamic.Selectors.AbpApiControllerActionSelector.GetActionDescriptorByActionName(HttpControllerContext controllerContext, DynamicApiControllerInfo controllerInfo, String actionName) in D:\Halil\GitHub\aspnetboilerplate\src\Abp.Web.Api\WebApi\Controllers\Dynamic\Selectors\AbpApiControllerActionSelector.cs:line 103\r\n   at Abp.WebApi.Controllers.Dynamic.Selectors.AbpApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext) in D:\Halil\GitHub\aspnetboilerplate\src\Abp.Web.Api\WebApi\Controllers\Dynamic\Selectors\AbpApiControllerActionSelector.cs:line 56\r\n   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at Castle.Proxies.DynamicApiController`1Proxy.ExecuteAsync_callback(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at Castle.Proxies.Invocations.ApiController_ExecuteAsync.InvokeMethodOnTarget()\r\n   at Castle.DynamicProxy.AbstractInvocation.Proceed()\r\n   at Abp.WebApi.Controllers.Dynamic.Interceptors.AbpDynamicApiControllerInterceptor`1.Intercept(IInvocation invocation) in D:\Halil\GitHub\aspnetboilerplate\src\Abp.Web.Api\WebApi\Controllers\Dynamic\Interceptors\AbpDynamicApiControllerInterceptor.cs:line 57\r\n   at Castle.DynamicProxy.AbstractInvocation.Proceed()\r\n   at Castle.Proxies.DynamicApiController`1Proxy.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

**Comment by hikalkan** [comment]
Which version? ASP.NET Core or ASP.NET MVC 5.x?

**Comment by nccheckcashing** [comment]
ASP.NET MVC 5.x

**Comment by hikalkan** [comment]
Thanks, I'm checking it.

**Comment by hikalkan** [comment]
I just run the project (from Github) and it worked. Did you downloaded from Github or from the Codeproject article?

**Comment by nccheckcashing** [comment]
I download from Github (https://github.com/aspnetboilerplate/aspnetboilerplate-samples/tree/master/SimpleTaskSystem).

**Comment by hikalkan** [comment]
Hi,

The problem is not database actually. Are you manually calling web API from browser address bar? Your exception is that:

"There is an action GetTasks defined for api controller tasksystem/task but with a different HTTP Verb. Request verb is GET. It should be Post"

Normally, all method calls are made via post. I didn't understand why your application tries to do GET instead of POST.

**Comment by nccheckcashing** [comment]
Hello Hikalkan, 
I tested API using POSTman extension and confirmed the APIs are working fine. It was the client side issue but all your codes are fine. So, I rebooted the system and launched VS 2015 again. Fortunately, the demo code was working fine. I don't know the reason. Anyway Thank you for your help and amazing framework!
