### ISSUE TITLE
Where can l find Abp.Web.Api.Swagger dll

### ISSUE THREAD

**Issue by LiuXiao617111** [aspnetboilerplate/aspnetboilerplate-samples#21]
1.  l can't find Abp.Web.Api.Swagger in nuget but  you use it in AbpSwagger.Tests. How l can find it.
2.  Abp.Application.Services.Attributes and Abp.Application.Services.Dto can't find even if l reference the Abp.Application dll

**Comment by hikalkan** [comment]
There is no such an official package. Maybe you are searching for https://github.com/yuzukwok/Abp.Web.Api.SwaggerTool

Where we use it?

**Comment by LiuXiao617111** [comment]
![image](https://cloud.githubusercontent.com/assets/8858358/24888801/5ff1a00a-1e98-11e7-88b5-7c562e53f1d5.png)
![image](https://cloud.githubusercontent.com/assets/8858358/24888804/66d0e318-1e98-11e7-8a61-dce2c094f4e9.png)

**Comment by hikalkan** [comment]
@carldai0106 Do you know that? I can't remember now it.

**Comment by LiuXiao617111** [comment]
l find it in 
![Uploading QQ图片20170411155200.png…]()
may be it is to old.

**Comment by hikalkan** [comment]
Anyway, there is no such a package and no need to it to use swagger within ABP.

**Comment by LiuXiao617111** [comment]
thank you
