### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by reubenwarwema** [aspnetboilerplate/aspnetboilerplate-samples#24]
Not sure is its the right place to ask but I'd be glad to get some assistance 

I  tried following the SimpleTaskSolution tutorial for ASP.NET MVC, AngularJS, EF

Here is my Order and Discipline classes

```

 public class Order : Entity<Guid>, IFullAudited
    {
		 public virtual string orderTopic { get; set; }
		 public virtual Guid disciplineId { get; set; }
		 ForeignKey("disciplineId")]
                 public virtual Disciplines.Discipline discipline { get; set; }
	}
	
	 public class Discipline : Entity<Guid>
          {
        public virtual string disciplineName { get; set; }
        public virtual double disciplinePrice { get; set; }
        public virtual ICollection<Subjects.Subject> subjects { get; set; }
        public virtual ICollection<Orders.Order> orders { get; set; }
    }
	
```
Here are my ApplicationServices

```
	public interface IDisciplineAppService : IApplicationService
    {
        [HttpGet]
       Task<GetAllDisciplinesOutput> GetAllDisciplines();
    }
	 public interface IOrderAppService : IApplicationService
    {
        [HttpGet]
        GetOrdersOutput GetOrders(GetOrderInput input);
    }
	
```
And lastly, maybe not least :-) AngularJS controllers
			---mastlistlist.js---

```
            vm.refreshOrders = function() {
                abp.ui.setBusy( //Set whole page busy until getTasks complete
                    null,
                    orderService.getOrders({ state: $scope.selectedOrderStatus > 0 ? $scope.selectedOrderStatus : null
                    }).then(function(result) {
                        vm.orders = result.orders;
                        console.log(result);
                    })
                );
            };


```
			---neworder.js---
	
Additionally, I have added the method
	 .WithConventionalVerbs()
to the projects DynamicApiControllerBuilder

and have the following scripts in my layout page, alongside the masterlist.js and neworder.js

```
	<script src="~/Abp/Framework/scripts/libs/angularjs/abp.ng.js"></script>
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/api/AbpServiceProxies/GetAll?type=angular"></script>
    <script src="~/AbpScripts/GetScripts" type="text/javascript"></script>
	
```
Yet i get the error: on both pages for adding an order and masterlist(displaying orders). Please assist. What am i missing?

```
{"result":null,"targetUrl":null,"success":false,"error":{"code":0,"message":"An internal error occurred during your request!","details":null,"validationErrors":null},"unAuthorizedRequest":false,"__abp":true}

```

**Comment by ismcagdas** [comment]
Can you check Logs.txt file under your web project ?
It should contain detailed error message.

**Comment by reubenwarwema** [comment]
What should I look for in the Log.txt file?

**Comment by ismcagdas** [comment]
Is there any error message ? You can try same action and see if app writes any error message to Logs.txt.

**Comment by reubenwarwema** [comment]
After several attempts, and a thorough review of my attached log file, I think the issue lies with my OrderDto mappings. Cause, now I have the error  below when I try to list my orders.GET /api/services/app/order/GetOrders 500(internal server error)My new order page has no error but still, my discipline dropdown-menu won't get populated.

**Comment by ismcagdas** [comment]
Can you share log file, entity and dto ?

**Comment by reubenwarwema** [comment]
Sent from my BlackBerry 10 smartphone.

**Comment by ismcagdas** [comment]
I think it does not include files when you reply email, see https://github.com/aspnetboilerplate/aspnetboilerplate-samples/issues/24#issuecomment-302002645

**Comment by reubenwarwema** [comment]
[Logs(1).txt](https://github.com/aspnetboilerplate/aspnetboilerplate-samples/files/1006817/Logs.1.txt)

[OrderDto.zip](https://github.com/aspnetboilerplate/aspnetboilerplate-samples/files/1006819/OrderDto.zip)

**Comment by ismcagdas** [comment]
According to Logs, you need to add [AutoMap(typeof(Order))] attribute to your OrderDto.
You can read this document for more info https://aspnetboilerplate.com/Pages/Documents/Object-To-Object-Mapping#auto-mapping-attributes

**Comment by reubenwarwema** [comment]
Thanks...worked like a charm... :-)
