### ISSUE TITLE
Retrieving Related Records

### ISSUE THREAD

**Issue by reubenwarwema** [aspnetboilerplate/aspnetboilerplate-samples#26]
I have a table(entity) order that has a one-to-many relation to discipline.
I can successfully insert and read the order(entity) using the GetAllBinding() method.
However, the object returned to my view does not include data(related row) from discipline.
PS: I have not implemented any custom Repository other than IRepositories and its default members.

OrderAppService
```
 public GetOrdersOutput GetAll()
        {
            var orders = _orderRepository.GetAllIncluding();
            return new GetOrdersOutput
            {
                Orders = _objectMapper.Map<List<OrderDto>>(orders)
            };
        }
```
OrderDto
```
 [AutoMap(typeof(Order))]
    public class OrderDto : EntityDto<Guid>
    {
        public Guid? disciplineId { get; set; }
        public string disciplineName { get; set; }
     }
```

Order(Entity)

```
 public class Order : Entity<Guid>, IFullAudited
    {
        public virtual string orderTopic { get; set; }
        public virtual string orderDescriptions { get; set; }
        
        public virtual Guid disciplineId { get; set; }
        [ForeignKey("disciplineId")]
        public virtual Disciplines.Discipline discipline { get; set; }
    }
```

Discipline(Entity)
```
 public class Discipline : Entity<Guid>
    {
        public virtual string disciplineName { get; set; }
        public virtual double disciplinePrice { get; set; }
        public virtual ICollection<Orders.Order> orders { get; set; }
   }
```
In my view, I return an OrderDto(mapped) to Order(entity). However disciplineName value is NULL.

This will solve half my problem:
The other half a filtering many-to-many drop down.

I have two entities that have a many-to-many relation. Please direct me to where i can look at how to populate a dropdown based on the value from another dropdown.

Thanks in advance

**Comment by hikalkan** [comment]
Hi,

None of your problems related to ABP, but I will help as much as I can:

1. If you are using EF Core, it does not support lazy loading. You should include it like var orders = _orderRepository.GetAllIncluding(o => o.discipline);
2. I suggest you to use PascalCase naming for entity properties, automapper uses naming for automapping.
3. Automapper can not map discipline.disciplineName to disciplineName. First, make properties PascalCase and rename disciplineName to DisciplineDisciplineName in your DTO. Or better, rename DisciplineName to Name in your Discipline entity.

For more, I suggest you to read automapper document.
