### ISSUE TITLE
[UPDATE] ConsoleRemoteWebApiCall

### ISSUE THREAD

**Issue by dawsidious** [aspnetboilerplate/aspnetboilerplate-samples#34]
Hello, 

Is it possible to update ConsoleRemoteWebApiCall sample with latest version of http://xxxx.demo.aspnetzero.com ?

When I try the sample it gave me : 

![sample](https://user-images.githubusercontent.com/4093902/31879948-4fdb4370-b7df-11e7-88c1-6ed1c81207ea.JPG)

(ps : my end goal is an UWP client with webapi call)

thanks for your help :)

**Comment by hikalkan** [comment]
Thank you for pointing that, we will upgrade it.
