### ISSUE TITLE
Hello, IdentityServer4 update does not use UseIdentityServerAuthentication method, then how to integrate IdentityServer4

### ISSUE THREAD

**Issue by MrHujing** [aspnetboilerplate/aspnetboilerplate-samples#35]
Hello, IdentityServer4 update does not use UseIdentityServerAuthentication method, then how to integrate IdentityServer4

**Comment by ismcagdas** [comment]
Hi @MrHujing, we haven't upgraded our samples to Identity Server 4 yet.

**Comment by MrHujing** [comment]
Can you tell me how to use it? Or what document reference?

**Comment by hikalkan** [comment]
Documentation is updated: https://aspnetboilerplate.com/Pages/Documents/Zero/Identity-Server
This documentation works with our [module-zero-core-template](https://github.com/aspnetboilerplate/module-zero-core-template).

**Comment by acjh** [comment]
Sample was updated:

https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/0e9cecc735c799aa2f565b602720939633b213c8/IdentityServerDemo/src/IdentityServerDemo.Web.Mvc/Startup/Startup.cs#L83-L90
