### ISSUE TITLE
Upgrade all samples and articles to ABP v3.4.0

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/aspnetboilerplate-samples#37]
(after ABP v3.4 release)

### Projects

It's appreciated if anyone want to update any of the following projects.

- [ ] SimpleTaskSystem-Core
- [ ] SimpleTaskSystem
- [ ] AbpEfConsoleApp
- [ ] AbpSwaggerDemo
- [ ] AbpWpfDemo
- [ ] BackgroundJobAndNotificationsDemo
- [ ] ConsoleRemoteWebApiCall
- [ ] IdentityServerDemo
- [ ] InterceptionDemo
- [ ] KendoUiDemo
- [ ] MultipleDbContextDemo
- [ ] OrganizationUnitsDemo
- [ ] PlugInDemo
- [ ] StoredProcedureDemo
- [ ] TestProjects

### Articles

We will update these articles after samples projects have been updated.

- [ ] http://www.codeproject.com/Articles/1115763/Using-ASP-NET-Core-Entity-Framework-Core-and-ASP-N
- [ ] http://www.codeproject.com/Articles/791740/Using-AngularJs-ASP-NET-MVC-Web-API-and-EntityFram
- [ ] https://www.codeproject.com/Articles/1043326/A-Multi-Tenant-SaaS-Application-With-ASP-NET-MVC-A
- [ ] https://www.codeproject.com/Articles/871786/Unit-testing-in-Csharp-using-xUnit-Entity-Framewor
- [ ] https://www.codeproject.com/Articles/1080517/Aspect-Oriented-Programming-using-Interceptors-wit
- [ ] https://www.codeproject.com/Articles/1189662/Running-ASP-NET-Boilerplate-Module-Zero-Core-Templ
- [ ] https://www.codeproject.com/Articles/1199648/Using-Stored-Procedure-User-Defined-Function-and-V

**Comment by natiki** [comment]
I will do a simple console project and also ConsoleRemoteWebApiCall.

**Comment by hikalkan** [comment]
We are upgrading all samples. So, closing this issue.

**Comment by alirizaadiyahsi** [comment]
Related PR https://github.com/aspnetboilerplate/aspnetboilerplate-samples/pull/42
