### ISSUE TITLE
Is there a MultipleDbContextDemo by ABP.AspNetCore

### ISSUE THREAD

**Issue by wuyi23** [aspnetboilerplate/aspnetboilerplate-samples#49]
Hi,is there a MultipleDbContextDemo by ABP.AspNetCore?

**Comment by ismcagdas** [comment]
@wuyi23 currently no. Do you have a problem about using two DB Contexts ? If so, we can try to help.

**Comment by wuyi23** [comment]
I don't konw how to Create other DbContext，Do I need to Create  class like RobotAppDbContextFactory and RobotAppDbContextConfigurer?

**Comment by hikalkan** [comment]
You can create two different projects for each dbcontext.

**Comment by wuyi23** [comment]
@hikalkan First,I create two different projects ,but there are a lot of problems with default initialization.
Then,I try to create other DbContext in the same project.They can access  the database when two dbcontexts are not user in the same AppService.When in the same AppService,they will used the same currentdbcontext, and then an error occurred.
How can I use tow dbcontext in the same AppService?Hope you  reply,Thank you!

**Comment by ismcagdas** [comment]
@wuyi23 can you share your DbContext classes ?

**Comment by wuyi23** [comment]
public class UuvDbContext : AbpDbContext
    {
        public virtual DbSet<UuvUsers> UuvUsers { get; set; }

        public virtual DbSet<Organizations> Organizationss { get; set; }
        public UuvDbContext(DbContextOptions<UuvDbContext> options) : base(options)
        {
        }
    }

**Comment by ismcagdas** [comment]
@wuyi23 thanks, this seems fine. Can you also share the code where you configure your DbContext's connection ?

**Comment by wuyi23** [comment]
public class RobotAppEntityFrameworkModule : AbpModule
    {
        /* Used it tests to skip dbcontext registration, in order to use in-memory database of EF Core */
        public bool SkipDbContextRegistration { get; set; }

        private readonly IConfigurationRoot _appConfiguration;

        public RobotAppEntityFrameworkModule(IHostingEnvironment env)
        {
            _appConfiguration = AppConfigurations.Get(env.ContentRootPath, env.EnvironmentName, env.IsDevelopment());
        }

        public bool SkipDbSeed { get; set; }

        public override void PreInitialize()
        {
            if (!SkipDbContextRegistration)
            {
                Configuration.Modules.AbpEfCore().AddDbContext<RobotAppDbContext>(options =>
                {

                    if (options.ExistingConnection != null)
                    {
                        RobotAppDbContextConfigurer.Configure(options.DbContextOptions, options.ExistingConnection);
                    }
                    else
                    {
                        RobotAppDbContextConfigurer.Configure(options.DbContextOptions, options.ConnectionString);
                    }
                });
            }
            Configuration.Modules.AbpEfCore().AddDbContext<UuvDbContext>(options =>
            {
                var configuration = _appConfiguration["ConnectionStrings:UUVService"];
                options.DbContextOptions.UseSqlServer(configuration);
            });
        }

        public override void Initialize()
        {
            IocManager.RegisterAssemblyByConvention(typeof(RobotAppEntityFrameworkModule).GetAssembly());
        }

        public override void PostInitialize()
        {
            if (!SkipDbSeed)
            {
                SeedHelper.SeedHostDb(IocManager);
            }
        }
    }



then appsetting.json file configure like this:
  "ConnectionStrings": {
    "Default": "Server=192.168.XX.XX; Database=XXX; User ID=sa; Password=XXX;",
    "UUVService": "Server=192.168.XX.XX; Database=XXX;User ID=uuv;Password=XXX;"
  },

**Comment by ismcagdas** [comment]
@wuyi23 I have created a demo for using multiple dbContext in Entity Framework Core. You can check it here https://github.com/aspnetboilerplate/aspnetboilerplate-samples/tree/master/MultipleDbContextEfCoreDemo.

The main thing is MyConnectionStringResolver class which decides the connection string for DbContexts.

**Comment by ismcagdas** [comment]
@wuyi23 please reopen a seperate issue if it doesn't work for you.

**Comment by wuyi23** [comment]
@ismcagdas Thanks a lot!It solves my problem perfectly.
