### ISSUE TITLE
BrowserModule already defined

### ISSUE THREAD

**Issue by Worthy7** [aspnetboilerplate/aspnetboilerplate-samples#50]
https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/19c888bcd32af86c511fcc809d9c0e3a7fd3da5a/ModuleZeroCoreWebFarm/angular/src/root.module.ts#L49

Having this line causes an error that BrowserModule is already loaded in the app (because it's also defined in App.Module.ts. It needs removing from App.Module I think.

**Comment by ismcagdas** [comment]
@Worthy7 I have installed packages using yarn and couldn't see this error. Have you installed packages using npm ? As far as I remember, this problem happens when angular version is updated.

Anyway, we should also sync this sample with the latest version of module-zero-core-template.

**Comment by ismcagdas** [comment]
for now you can use https://yarnpkg.com/lang/en/ to install npm dependencies. We upgrade angular version of this sample to v5.x.
