### ISSUE TITLE
Interceptor is not working for methods which are not used for CRUD and not working for async methods

### ISSUE THREAD

**Issue by Bijayakumar1990** [aspnetboilerplate/aspnetboilerplate-samples#53]
I am really feeling the pain to write my own interceptors as per my application's requirements. If I write some method not used as CRUD (e.g GetEmployeeDetails(), ChangeStatus(), etc..). Also not properly working for async methods. In a top note its working for some methods and not working for some. How can I resolve this issue. It will be a great help, if u can clarify this. Thanks

**Comment by hikalkan** [comment]
Have you seen this: http://www.aspnetboilerplate.com/Pages/Documents/Articles/Aspect-Oriented-Programming-using-Interceptors/index.html

Note that (as I know) it's not possible to perform async code before the actual code in the interceptor. But you can run async code after the actual code. My article shows it.

**Comment by Bijayakumar1990** [comment]
Yes I had gone through it and had done exactly what you have suggested. Its working perfectly fine for the appservices provided by you (RoleAppServise, UserAppService), but not working for the AppServices created by me as per my application requires. Might be the new appservices created by me are not being registered for interceptor. Below are the code written by me to register the services to be intercepted and one sample AppService created by me.

**My registrar code:**
public class Kare4uExecutionTimeInterceptorRegister
    {
        public static void Initialize(IKernel kernel)
        {
            kernel.ComponentRegistered += Kernel_ComponentRegistered;
        }

        private static void Kernel_ComponentRegistered(string key, IHandler handler)
        {
            if (typeof(IApplicationService).IsAssignableFrom(handler.ComponentModel.Implementation))
            {
                handler.ComponentModel.Interceptors.Add(new InterceptorReference(typeof(Kare4uExecutionTimeInterceptor)));
                handler.ComponentModel.Interceptors.Add(new InterceptorReference(typeof(Kare4uExecutionTimeInterceptorAsync)));
                handler.ComponentModel.Interceptors.Add(new InterceptorReference(typeof(Kare4ueExecutionTimeWithPostAsyncActionInterceptor)));
            }
        }
    }

**My Appservice**

using Abp.Application.Services;
using Abp.Domain.Repositories;
using kare4u.Kare4uModules.Dtos;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.Linq;
using System.Reflection;

namespace kare4u.Kare4uModules
{
    public class ModuleAppService : ApplicationService
    {
        private readonly IRepository<Kare4uModuleConfig, int> _kare4uModuleConfigRepository;
        public ModuleAppService(IRepository<Kare4uModuleConfig, int> kare4uModuleConfigRepository)
        {
            _kare4uModuleConfigRepository = kare4uModuleConfigRepository;
        }
        /// <summary>
        /// This method will be used for getting all 
        /// the modules.
        /// </summary>
        /// <returns></returns>
        public Kare4uModuleList GetAll()
        {
            var assemblyInfo = new Kare4UAssemblyInfo();
            var modules = assemblyInfo.GetListOfRelevantModules();
            var moduleNames = new Kare4uModuleList { Modules = new List<string>() };
            foreach (var module in modules)
            {
                moduleNames.Modules.Add(module.Name);
            }
            return moduleNames;
        }
    }
}

**Comment by acjh** [comment]
See #3237
