### ISSUE TITLE
new version how to config MenuItem  icon 

### ISSUE THREAD

**Issue by w757703598** [aspnetboilerplate/aspnetboilerplate-samples#55]
old version:
new MenuItemDefinition(
                        "About",
                        L("About"),
                        url: "About",
                        icon: "fa fa-info"
                    )
new version:
new MenuItemDefinition(
                        PageNames.About,
                        L("About"),
                        url: "About",
                        icon: "info"
                    )

**Comment by ismcagdas** [comment]
@w757703598 which template you are using ? You can share a screenshot what you have selected while downloading the project on http://aspnetboilerplate.com/templates.

**Comment by acjh** [comment]
The free template uses [AdminBSB](https://github.com/gurayyarar/AdminBSBMaterialDesign), which [supports Material Design Icons](https://gurayyarar.github.io/AdminBSBMaterialDesign/pages/ui/icons.html).

**Comment by acjh** [comment]
Answered in this SO question: [How to use icons with NavigationProvider that are not Material Design?](https://stackoverflow.com/a/50502580/8601760)
