### ISSUE TITLE
Question: Database User Defined Function

### ISSUE THREAD

**Issue by jguinto-komaa** [aspnetboilerplate/aspnetboilerplate-samples#59]
Hi, Just want to know if its possible to implement User Defined function using this [method](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#database-scalar-function-mapping) instead of [this](https://aspnetboilerplate.com/Pages/Documents/Articles/Using-Stored-Procedures,-User-Defined-Functions-and-Views/index.html)

Because currently im having an issue here in line number 98: 

![image](https://user-images.githubusercontent.com/40725869/43620421-139f7d14-96c2-11e8-81ad-f641ad04a711.png)

were originally that line shouldn't be executed.

Thanks you so much.

**Comment by hikalkan** [comment]
What EF / EF Core supports, you can use in ABP.
