### ISSUE TITLE
MultipleDbContextEfCoreDemo

### ISSUE THREAD

**Issue by liaozb** [aspnetboilerplate/aspnetboilerplate-samples#64]
How to query cross-database two-table Association

**Comment by acjh** [comment]
...separately?

**Comment by liaozb** [comment]
from a in _courseRepository.GetAll() join b in _personRepository.GetAll() on a.Id equals b.Id

**Comment by ujjvalomyinfotech** [comment]
from a in _courseRepository.GetAll() join a in _personRepository.GetAll() on a.Id equals b.Id

**Comment by ujjvalomyinfotech** [comment]
> from a in _courseRepository.GetAll() join b in _personRepository.GetAll() on a.Id equals b.Id

need to join on b
