### ISSUE TITLE
Cannot compile InterceptionDemo and AbpSwaggerDemo

### ISSUE THREAD

**Issue by juniormayhe** [aspnetboilerplate/aspnetboilerplate-samples#67]
Are these projects in github actually working samples? I just cannot compile some of them, Tried to restore and build but there are missing classes, eg: at _InterceptionDemo_.Web -> _AccountController_:

- Tenant is missing
- TenantManager is missing
- UserManager requires two type arguments
- RoleManager requires two type arguments
- LoginManager is missing
- User is missing

**Comment by ismcagdas** [comment]
@juniormayhe could it be something else ? As you can see, the AccountController is here https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/master/InterceptionDemo/InterceptionDemo.Web/Controllers/AccountController.cs

**Comment by juniormayhe** [comment]
I am closing this. I think it would be needed that some contributor restests all demo projects here to double check if they really build and runs at least in VS2017

**Comment by ismcagdas** [comment]
@juniormayhe do you have .NET Core 3.0 SDK Preview installed ?
