### ISSUE TITLE
KendoUIDemo - readme.md link for grid init code broken

### ISSUE THREAD

**Issue by schlarmage** [aspnetboilerplate/aspnetboilerplate-samples#70]
KendoUIDemo - The link to the grid init code in readme.md is broken - would you please fix or provide the link?

Cheers

**Comment by maliming** [comment]
I think it should be: https://github.com/aspnetboilerplate/aspnetboilerplate-samples/blob/master/KendoUiDemo/src/AbpKendoDemo.Web.Mvc/wwwroot/view-resources/Views/Users/Index.js
