### ISSUE TITLE
AutoMapper not working

### ISSUE THREAD

**Issue by Otgontugs** [aspnetboilerplate/aspnetboilerplate-samples#9]
aspnetboilerplate-samples/AbpEfConsoleApp/AbpEfConsoleApp/Program.cs

When i use Console application, Maps created inside any module initialization not working, even in Program.cs file. Throwing unsupported mapping exception

**Comment by hikalkan** [comment]
Have you defined a module in console project and add DependsOn attribute for AbpAutoMapperModule type?

**Comment by jaq316** [comment]
I looked at the DTO documentation and couldn't find mention of this. Can we add this?

**Comment by hikalkan** [comment]
Hi,

Actually this is not related or special to DTOs or automappings. When you use an ABP module, you should add a DependsOn attribute to your module. So, forst you should have a module to define dependencies :)
